### PR TITLE
change to get env vars for stub from a configmap

### PR DESCRIPTION
**Pull request by gilesheron**
now uses a config map to get env vars for the stub.

no need for stub to have a config map itself so removed all that.

current code hard-wires the env var names.  Should be possible to read them from the file and iterate?

### CODE REVIEW

**Comment by brecode** [comment]
What do you think of using the same technique the code currently implements for getting image name/tag/pull policy. That way there is no need for the user to explicitly create a config map. Someone can pass hard-wired env variables through the deployment spec. Have sample code here: [diff](https://github.com/media-streaming-mesh/msm-admission-webhook/compare/main...brecode:env). Same outcome without configmap step that will need to be deployed before msm-webhook

**Comment by brecode** [comment]
If we go the configMap route, then an implementation that adds reads, iterates and injects all KVs from the named CM would be better

**Comment by gilesheron** [comment]
Yeah – could do. I guess was thinking that the env vars there at the moment are used to set stuff that isn’t stub env vars, and wanted to keep setting stub env vars separate.

I guess we could prefix those vars for clarity – e.g. STUB_LOG_LEVEL, STUB_DATA_PLANE, STUB_CONTROL_PLANE?

From: Nikos ***@***.***>
Date: Wednesday, 24 August 2022 at 10:22
To: media-streaming-mesh/msm-admission-webhook ***@***.***>
Cc: Giles Heron (giheron) ***@***.***>, Author ***@***.***>
Subject: Re: [media-streaming-mesh/msm-admission-webhook] change to get env vars for stub from a configmap (PR #1)

What do you think of using the same technique the code currently implements for getting image name/tag/pull policy. That way there is no need for the user to explicitly create a config map. Someone can pass hard-wired env variables through the deployment spec. Have sample code here: diff<https://github.com/media-streaming-mesh/msm-admission-webhook/compare/main...brecode:env>. Same outcome without configmap step that will need to be deployed before msm-webhook

**Comment by gilesheron** [comment]
Yeah – that’d probably be the optimal solution.  But am not quite sure how we do that 😉

From: Nikos ***@***.***>
Date: Wednesday, 24 August 2022 at 10:24
To: media-streaming-mesh/msm-admission-webhook ***@***.***>
Cc: Giles Heron (giheron) ***@***.***>, Author ***@***.***>
Subject: Re: [media-streaming-mesh/msm-admission-webhook] change to get env vars for stub from a configmap (PR #1)

If we go the configMap route, then an implementation that adds reads, iterates and injects all KVs from the named CM would be better

**Comment by brecode** [comment]
It would get more complex as the webhook would need access to configMap resources, which is a bit out of context for this webhook. I say we keep it simple via passing the env vars as pod env vars :)

**Comment by gilesheron** [comment]
> 

Sure - let's stick with env vars.  and maybe make the prefix "MSM_" rather than "STUB_"

do you want to do the PR and I merge it, or vice-versa?

**Comment by gilesheron** [comment]
> Sure - let's stick with env vars. and maybe make the prefix "MSM_" rather than "STUB_"
> 
> do you want to do the PR and I merge it, or vice-versa?

actually I guess you already did it?  I'll merge.  but will then change LOG_LVL to MSM_LOG_LVL as we're already passing LOG_LVL var into the webhook I think?

**Pull request merged**
