### PR TITLE
Webhook cfg

### PR DESCRIPTION
**Pull request by john-a-joyce**

### CODE REVIEW

**Review by gilesheron — COMMENTED** [review]
looks good generally.   not sure why go.mod has requirements on istio though?

**Comment by john-a-joyce** [comment]
@gilesheron - I looked at some Istio code that did something close to what I needed.   My IDE or the build step must have updated the go.mod.  I made sure all the Istio imports weren't needed and thought " go mod tidy" would clean things up.  Glad you noticed I will remove those modules.   Also with the new CI step I need to run linters and lots of things being flagged for change so I need to update this PR.

**Comment by john-a-joyce** [comment]
Sorry - this grew so much but when the lint check was failing I started checking against a pretty aggressive set of linters.  Now its back only the linters Mark added.

**Review by gilesheron — APPROVED** [review]
LGTM

**Pull request merged**
